# ── Stage 1: build dependencies in a separate layer for cache efficiency ──
FROM python:3.11-slim AS builder

WORKDIR /build

# Install build tools (needed by some Python wheels)
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache-dir --prefix=/install -r requirements.txt


# ── Stage 2: lean runtime image ───────────────────────────────────────────
FROM python:3.11-slim AS runtime

LABEL maintainer="ml-team" \
      description="Iris Species Classifier REST API" \
      version="1.0.0"

# Create a non-root user for security
RUN useradd --create-home --shell /bin/bash appuser

WORKDIR /app

# Copy installed packages from builder stage
COPY --from=builder /install /usr/local

# Copy application source
COPY app/ ./app/

# Copy the trained model artefact
# (model.pkl must be generated by `python training/train.py` before docker build)
COPY model.pkl .

# Drop privileges
USER appuser

# Expose the API port
EXPOSE 8000

# Health check – the container orchestrator uses this to gate traffic
HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" \
    || exit 1

# Default command: run the API with production-suitable settings
CMD ["uvicorn", "app.main:app", \
     "--host", "0.0.0.0", \
     "--port", "8000", \
     "--workers", "2", \
     "--log-level", "info", \
     "--no-access-log"]
